[package]
name = "hello-world"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hello-world-macro = {path = "./hello-world-macro"}
make-public-macro = {path = "./make-public-macro"}